### ISSUE TITLE
How can i set trigger for validation

### ISSUE THREAD

**Issue by leonardotessaroalves** [davestewart/vee-element#12]
I need disable validation and just validate onSubmit. thks

**Comment by hardeepmonty** [comment]
This is something similar to what I require, I want to use Element's blur / change trigger to fire validations

**Comment by leonardotessaroalves** [comment]
my mistake, its just use the right propertie on el-form and turn off :validate-on-rule-change="false"

**Comment by davestewart** [comment]
Thanks for feeding back!
