### ISSUE TITLE
Debounced validation

### ISSUE THREAD

**Issue by Artem-Schander** [davestewart/vee-element#23]
Hi,
Thank you for your work.
Is there a way to debounce custom rules? For example by using something like[ this inline attribute](https://baianat.github.io/vee-validate/examples/debounce.html)?

**Comment by davestewart** [comment]
Oh crikey. No idea!

Sorry I haven't managed to look at this project for ages :(

**Comment by Artem-Schander** [comment]
too bad..
If you want to bring the project back to life again, contact me. I'll try to shovel free some time to collaborate.

For the time being i found a way to debounce .. so for anyone who googles it:

    import debounce from 'debounce-promise' // https://www.npmjs.com/package/debounce-promise
    import Api from './path/to/some/api/object'

    Validator.extend('unique_key', {
        validate: debounce((value, rule) => {

            return Api.validateKey(value)
                .then(valid => {
                    return {
                        valid,
                        data: {
                            message: 'This value is already taken.'
                        }
                    }
                })
        }, 300),
        getMessage: (field, params, data) => {
            return data.message;
        }
    })
