### ISSUE TITLE
Validations don't occur on blur and change events if rules is an object

### ISSUE THREAD

**Issue by arpit9295** [davestewart/vee-element#26]
An example is the `comment` field in the [complex example](https://vee-element.netlify.com/#/complex).

**Comment by arpit9295** [comment]
The reason it occurs is because of [the check by element form for skipping validations](https://github.com/ElemeFE/element/blob/dev/packages/form/src/form-item.vue#L291).

It has been fixed in #24 in [this commit](https://github.com/davestewart/vee-element/pull/24/commits/ca909c3d8a936cb8f9c4777fa255e3908b85c97a)

**Comment by whoisarpit** [comment]
This has been fixed by #24
