### ISSUE TITLE
Q: Does vee-element only work on the 2.1.0-beta.9 of vee-validate?

### ISSUE THREAD

**Issue by song4wk** [davestewart/vee-element#3]
Hi, Dave
This is Song.
I am trying to use your amazing plugin for vee-validate, that's wonderful!
But I think I need your help with it.

Versions

vee-validate: 2.1.0-beta.11
vue: 2.9.6

OS: Windows 10 pro v1803
Browser: Chrome 69.0.3497.100

Describe the problem

If run the demo on 2.1.0-beta.9 of vee-validate that's ok , but on 2.1.0-beta.11 error message shown as below:

![vee-validate-error-demo](https://user-images.githubusercontent.com/44188147/46995964-df163500-d155-11e8-98d1-0238d6179ee6.png)

Question:

1. Does vee-element only work on the 2.1.0-beta.9 of vee-validate?

2. If not how to dealing with the new version of vee-validate?

Thanks!

**Comment by song4wk** [comment]
I am sorry Dave, I got it as below~~
https://github.com/baianat/vee-validate/issues/1646

**Comment by kingjan1999** [comment]
So what exactly was your solution @song4wk ?

**Comment by song4wk** [comment]
＠kingjan1999

I just use the same version of vee-validate as the demo~~

**Comment by song4wk** [comment]
@davestewart 

I just wondering when it can work on the latest version of vee-validate?

**Comment by davestewart** [comment]
OK, let me look into this. 

Can you post relevant `package.json` dependencies ?

**Comment by song4wk** [comment]
@davestewart 

Sorry to bother you. Dave.

I just update the `vee-validate` and my `package.json`  is as below:

```json
{
  "name": "vee-element-demo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "element-ui": "^2.4.8",
    "object-get": "^2.1.0",
    "vee-element": "^1.0.0-alpha",
    "vee-validate": "^2.1.0-beta.11",
    "vue": "^2.5.17",
    "vue-router": "^3.0.1"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.4",
    "@vue/cli-plugin-eslint": "^3.0.4",
    "@vue/cli-service": "^3.0.4",
    "@vue/eslint-config-standard": "^3.0.4",
    "node-sass": "^4.9.3",
    "sass-loader": "^7.1.0",
    "vue-template-compiler": "^2.5.17"
  }
}

```

Thanks!

**Comment by kingjan1999** [comment]
I created a workaround in https://github.com/kingjan1999/vee-element/commit/2a4cdef16a3e3fdc78b220313825840fcfbdedfa which makes the demo work, but I feel like this is not a proper solution to the problem.

**Comment by song4wk** [comment]
@kingjan1999 

Thank you, I think it will be helpful for me.^_^
