### ISSUE TITLE
Add runtime error message

### ISSUE THREAD

**Issue by Stenfrank** [davestewart/vee-element#36]
With "vee-validate" you can add error as follows but with "vee-element" it doesn't work:

```
this.$validator.errors.add({
    field: 'name',
    msg: 'The name already exists',
});
```

**Comment by whoisarpit** [comment]
Yes, this is not a supported functionality as the `errorBag` is not exposed on a per form item basis. (which is the only way really through which one could add new errors to that form item)

If the current code allows it, we can will the functionality. If you have any ideas please add a pull request :)
