### ISSUE TITLE
you dead?

### ISSUE THREAD

**Issue by artem-schander** [davestewart/vee-element#56]
![lol-is-u-ded](https://user-images.githubusercontent.com/1243826/128220927-c57e2de8-84e8-4d0d-bcdd-7a68f4f8ae0c.jpg)

**Comment by davestewart** [comment]
Mainly!

**Comment by artem-schander** [comment]
\*sad noises\*

**Comment by davestewart** [comment]
What did you want to do / do you need?

It's a pretty simple library if you want to dig in!

- https://github.com/davestewart/vee-element/blob/master/src/main.js
- https://github.com/davestewart/vee-element/blob/master/src/drivers/vee.js

**Comment by artem-schander** [comment]
Yes.. I don‘t know if that makes much sense. Vee-element depends on an old vee-validate version.
On the one hand it would possibly take less time to dig into this lib and fix the issue, on the other hand if I refactor all the existing forms to use vee-validate v3 its more future proof. I‘ll see…

My problem is, that here and there async serverside validation does not work propery. The input field shows the validation error and is red, but the form passes the overall validation.
The strange thing is, that in other constellations the same validators are working flawlessly.


Why did you decide to abandon this project while still in alpha?

**Comment by davestewart** [comment]
I'm a contractor, so usually the case is that the client I'm working with will use Technology X and I'll develop OSS around that, then when I move on to a new client, I don't have access to the original codebase, so I don't get to use it any more.

I think that was the case here, which is a shame, as I really liked this project! I thought it was a creative way to solve an "unsolvable" problem.

Nothing to do with the code / approach though; I think that is solid-enough.

**Comment by artem-schander** [comment]
I see

**Comment by davestewart** [comment]
PRs are open. Happy to set up a proper versioned set of releases for Vue / Vee Validate versions...

**Comment by artem-schander** [comment]
Then you want to invest some time in this project? So not dead?
If so, I'll try to find some time and get a PR together to use the new vee-validate version.

**Comment by davestewart** [comment]
Well, it's still useful! I just don't use it these days 😺

**Comment by artem-schander** [comment]
Its useful indeed. I‘m using it for a huge project with many forms until now.

I have a similar situation with one of my OS projects (l5modular) which i have written some years ago but stopped using. Now I‘m just maintaining it as a sidequest.

No idea if you‘re up to date, but it is considerable to know that Vee-Validate can be used with Element UI without the need of extra packages like this one. But its not that nice. Much more markup and no centralized rules.
See https://vee-validate.logaretm.com/v2/examples/validation-providers.html

**Comment by whoisarpit** [comment]
@Artem-Schander If you're looking for some specific improvements on the library, do let us know!
I just couldn't think of many improvements other that moving to a newer version of vee-validate 😅
